# Generated by Django 5.1.2 on 2024-10-30 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 10, 30, 4, 22, 30, 67581, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
